# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-22 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allbooks',
            name='bookCoverImage',
            field=models.FileField(upload_to=b''),
        ),
        migrations.AlterField(
            model_name='allbooks',
            name='bookPDF',
            field=models.FileField(upload_to=b''),
        ),
        migrations.AlterField(
            model_name='allbooks',
            name='thumbnailImage',
            field=models.FileField(upload_to=b''),
        ),
    ]
