# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-13 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_auto_20190322_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='recentlyOpened',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=200)),
                ('bookName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.AllBooks')),
            ],
        ),
    ]
