# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-13 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0003_recentlyopened'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentlyopened',
            name='bookName',
            field=models.CharField(max_length=300),
        ),
    ]
