# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-13 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0004_auto_20190413_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='userFav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookName', models.CharField(max_length=300)),
                ('userName', models.CharField(max_length=200)),
            ],
        ),
    ]
