# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-15 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0005_userfav'),
    ]

    operations = [
        migrations.AddField(
            model_name='allbooks',
            name='bookPages',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='allbooks',
            name='review1',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='allbooks',
            name='review2',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='allbooks',
            name='review3',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='allbooks',
            name='secondName',
            field=models.CharField(default='', max_length=100),
        ),
    ]
