# Generated by Django 2.2.6 on 2019-10-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0006_auto_20190415_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allbooks',
            name='bookCoverImage',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='allbooks',
            name='bookPDF',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='allbooks',
            name='thumbnailImage',
            field=models.FileField(upload_to=''),
        ),
    ]
