# Generated by Django 2.2.6 on 2019-10-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0007_auto_20191022_0719'),
    ]

    operations = [
        migrations.CreateModel(
            name='userUploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookName', models.CharField(max_length=300)),
                ('userName', models.CharField(max_length=200)),
            ],
        ),
    ]
